package com.shinowit.dao.mapper;

import com.shinowit.entity.Memberinfo;
import com.shinowit.entity.MemberinfoCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MemberinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memberinfo
     *
     * @mbggenerated Wed Jan 14 09:50:25 CST 2015
     */
    int countByExample(MemberinfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memberinfo
     *
     * @mbggenerated Wed Jan 14 09:50:25 CST 2015
     */
    int deleteByExample(MemberinfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memberinfo
     *
     * @mbggenerated Wed Jan 14 09:50:25 CST 2015
     */
    int deleteByPrimaryKey(String memberid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memberinfo
     *
     * @mbggenerated Wed Jan 14 09:50:25 CST 2015
     */
    int insert(Memberinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memberinfo
     *
     * @mbggenerated Wed Jan 14 09:50:25 CST 2015
     */
    int insertSelective(Memberinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memberinfo
     *
     * @mbggenerated Wed Jan 14 09:50:25 CST 2015
     */
    List<Memberinfo> selectByExample(MemberinfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memberinfo
     *
     * @mbggenerated Wed Jan 14 09:50:25 CST 2015
     */
    Memberinfo selectByPrimaryKey(String memberid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memberinfo
     *
     * @mbggenerated Wed Jan 14 09:50:25 CST 2015
     */
    int updateByExampleSelective(@Param("record") Memberinfo record, @Param("example") MemberinfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memberinfo
     *
     * @mbggenerated Wed Jan 14 09:50:25 CST 2015
     */
    int updateByExample(@Param("record") Memberinfo record, @Param("example") MemberinfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memberinfo
     *
     * @mbggenerated Wed Jan 14 09:50:25 CST 2015
     */
    int updateByPrimaryKeySelective(Memberinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memberinfo
     *
     * @mbggenerated Wed Jan 14 09:50:25 CST 2015
     */
    int updateByPrimaryKey(Memberinfo record);

    List<Memberinfo> selectPage(MemberinfoCriteria example);

    String selectMaxPrimaryKeyValue();
//    自增
    Memberinfo selectMemberinfo(String membername, String password);

    Memberinfo selectMemPadd(String membername, String email);
}