package com.shinowit.dao.mapper;

import com.shinowit.entity.Memberinfo;
import com.shinowit.entity.MemberinfoCriteria;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface MemberinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memberinfo
     *
     * @mbggenerated Thu Dec 25 13:36:01 CST 2014
     */
    int countByExample(MemberinfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memberinfo
     *
     * @mbggenerated Thu Dec 25 13:36:01 CST 2014
     */
    int deleteByExample(MemberinfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memberinfo
     *
     * @mbggenerated Thu Dec 25 13:36:01 CST 2014
     */
    int deleteByPrimaryKey(String memberid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memberinfo
     *
     * @mbggenerated Thu Dec 25 13:36:01 CST 2014
     */
    int insert(Memberinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memberinfo
     *
     * @mbggenerated Thu Dec 25 13:36:01 CST 2014
     */
    int insertSelective(Memberinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memberinfo
     *
     * @mbggenerated Thu Dec 25 13:36:01 CST 2014
     */
    List<Memberinfo> selectByExample(MemberinfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memberinfo
     *
     * @mbggenerated Thu Dec 25 13:36:01 CST 2014
     */
    Memberinfo selectByPrimaryKey(String memberid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memberinfo
     *
     * @mbggenerated Thu Dec 25 13:36:01 CST 2014
     */
    int updateByExampleSelective(@Param("record") Memberinfo record, @Param("example") MemberinfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memberinfo
     *
     * @mbggenerated Thu Dec 25 13:36:01 CST 2014
     */
    int updateByExample(@Param("record") Memberinfo record, @Param("example") MemberinfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memberinfo
     *
     * @mbggenerated Thu Dec 25 13:36:01 CST 2014
     */
    int updateByPrimaryKeySelective(Memberinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memberinfo
     *
     * @mbggenerated Thu Dec 25 13:36:01 CST 2014
     */
    int updateByPrimaryKey(Memberinfo record);

    List<Memberinfo> selectPage(MemberinfoCriteria example);

    String selectMaxPrimaryKeyValue();

    Memberinfo selectMemberinfo(String membername, String password);

    Memberinfo selectMemPadd(String membername, String email);
}