package com.shinowit.dao.mapper;

import com.shinowit.entity.Merchandiseinfo;
import com.shinowit.entity.MerchandiseinfoCriteria;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface MerchandiseinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchandiseinfo
     *
     * @mbggenerated Tue Dec 30 09:13:22 CST 2014
     */
    int countByExample(MerchandiseinfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchandiseinfo
     *
     * @mbggenerated Tue Dec 30 09:13:22 CST 2014
     */
    int deleteByExample(MerchandiseinfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchandiseinfo
     *
     * @mbggenerated Tue Dec 30 09:13:22 CST 2014
     */
    int deleteByPrimaryKey(String merchandiseid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchandiseinfo
     *
     * @mbggenerated Tue Dec 30 09:13:22 CST 2014
     */
    int insert(Merchandiseinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchandiseinfo
     *
     * @mbggenerated Tue Dec 30 09:13:22 CST 2014
     */
    int insertSelective(Merchandiseinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchandiseinfo
     *
     * @mbggenerated Tue Dec 30 09:13:22 CST 2014
     */
    List<Merchandiseinfo> selectByExample(MerchandiseinfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchandiseinfo
     *
     * @mbggenerated Tue Dec 30 09:13:22 CST 2014
     */
    Merchandiseinfo selectByPrimaryKey(String merchandiseid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchandiseinfo
     *
     * @mbggenerated Tue Dec 30 09:13:22 CST 2014
     */
    int updateByExampleSelective(@Param("record") Merchandiseinfo record, @Param("example") MerchandiseinfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchandiseinfo
     *
     * @mbggenerated Tue Dec 30 09:13:22 CST 2014
     */
    int updateByExample(@Param("record") Merchandiseinfo record, @Param("example") MerchandiseinfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchandiseinfo
     *
     * @mbggenerated Tue Dec 30 09:13:22 CST 2014
     */
    int updateByPrimaryKeySelective(Merchandiseinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchandiseinfo
     *
     * @mbggenerated Tue Dec 30 09:13:22 CST 2014
     */
    int updateByPrimaryKey(Merchandiseinfo record);

    List<Merchandiseinfo> selectPage(MerchandiseinfoCriteria example);

    String selectMaxPrimaryKeyValue();

    List<Merchandiseinfo> selectMerchandise();

    List<Merchandiseinfo> selectMerchandiseList(String id);
}