package com.shinowit.dao.mapper;

import com.shinowit.entity.Merchandiseinfo;
import com.shinowit.entity.MerchandiseinfoCriteria;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface MerchandiseinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchandiseinfo
     *
     * @mbggenerated Wed Jan 14 09:50:25 CST 2015
     */
    int countByExample(MerchandiseinfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchandiseinfo
     *
     * @mbggenerated Wed Jan 14 09:50:25 CST 2015
     */
    int deleteByExample(MerchandiseinfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchandiseinfo
     *
     * @mbggenerated Wed Jan 14 09:50:25 CST 2015
     */
    int deleteByPrimaryKey(String merchandiseid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchandiseinfo
     *
     * @mbggenerated Wed Jan 14 09:50:25 CST 2015
     */
    int insert(Merchandiseinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchandiseinfo
     *
     * @mbggenerated Wed Jan 14 09:50:25 CST 2015
     */
    int insertSelective(Merchandiseinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchandiseinfo
     *
     * @mbggenerated Wed Jan 14 09:50:25 CST 2015
     */
    List<Merchandiseinfo> selectByExample(MerchandiseinfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchandiseinfo
     *
     * @mbggenerated Wed Jan 14 09:50:25 CST 2015
     */
    Merchandiseinfo selectByPrimaryKey(String merchandiseid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchandiseinfo
     *
     * @mbggenerated Wed Jan 14 09:50:25 CST 2015
     */
    int updateByExampleSelective(@Param("record") Merchandiseinfo record, @Param("example") MerchandiseinfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchandiseinfo
     *
     * @mbggenerated Wed Jan 14 09:50:25 CST 2015
     */
    int updateByExample(@Param("record") Merchandiseinfo record, @Param("example") MerchandiseinfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchandiseinfo
     *
     * @mbggenerated Wed Jan 14 09:50:25 CST 2015
     */
    int updateByPrimaryKeySelective(Merchandiseinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchandiseinfo
     *
     * @mbggenerated Wed Jan 14 09:50:25 CST 2015
     */
    int updateByPrimaryKey(Merchandiseinfo record);

    List<Merchandiseinfo> selectPage(MerchandiseinfoCriteria example);

    String selectMaxPrimaryKeyValue();

    //   自增
    List<Merchandiseinfo> selectMerchandise();

    List<Merchandiseinfo> selectMerchandiseList(String id);
}