package com.shinowit.entity;

import java.io.Serializable;

public class Chart implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table chart
     *
     * @mbggenerated Wed Jan 14 09:50:25 CST 2015
     */
    private static final long serialVersionUID = 1L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chart.Id
     *
     * @mbggenerated Wed Jan 14 09:50:25 CST 2015
     */
    private String id;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chart.count
     *
     * @mbggenerated Wed Jan 14 09:50:25 CST 2015
     */
    private Integer count;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chart.MemberID
     *
     * @mbggenerated Wed Jan 14 09:50:25 CST 2015
     */
    private String memberid;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chart.MerchandiseID
     *
     * @mbggenerated Wed Jan 14 09:50:25 CST 2015
     */
    private String merchandiseid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chart.Id
     *
     * @return the value of chart.Id
     * @mbggenerated Wed Jan 14 09:50:25 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chart.Id
     *
     * @param id the value for chart.Id
     * @mbggenerated Wed Jan 14 09:50:25 CST 2015
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chart.count
     *
     * @return the value of chart.count
     * @mbggenerated Wed Jan 14 09:50:25 CST 2015
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chart.count
     *
     * @param count the value for chart.count
     * @mbggenerated Wed Jan 14 09:50:25 CST 2015
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chart.MemberID
     *
     * @return the value of chart.MemberID
     * @mbggenerated Wed Jan 14 09:50:25 CST 2015
     */
    public String getMemberid() {
        return memberid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chart.MemberID
     *
     * @param memberid the value for chart.MemberID
     * @mbggenerated Wed Jan 14 09:50:25 CST 2015
     */
    public void setMemberid(String memberid) {
        this.memberid = memberid == null ? null : memberid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chart.MerchandiseID
     *
     * @return the value of chart.MerchandiseID
     * @mbggenerated Wed Jan 14 09:50:25 CST 2015
     */
    public String getMerchandiseid() {
        return merchandiseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chart.MerchandiseID
     *
     * @param merchandiseid the value for chart.MerchandiseID
     * @mbggenerated Wed Jan 14 09:50:25 CST 2015
     */
    public void setMerchandiseid(String merchandiseid) {
        this.merchandiseid = merchandiseid == null ? null : merchandiseid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chart
     *
     * @mbggenerated Wed Jan 14 09:50:25 CST 2015
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Chart other = (Chart) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
                && (this.getCount() == null ? other.getCount() == null : this.getCount().equals(other.getCount()))
                && (this.getMemberid() == null ? other.getMemberid() == null : this.getMemberid().equals(other.getMemberid()))
                && (this.getMerchandiseid() == null ? other.getMerchandiseid() == null : this.getMerchandiseid().equals(other.getMerchandiseid()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chart
     *
     * @mbggenerated Wed Jan 14 09:50:25 CST 2015
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getCount() == null) ? 0 : getCount().hashCode());
        result = prime * result + ((getMemberid() == null) ? 0 : getMemberid().hashCode());
        result = prime * result + ((getMerchandiseid() == null) ? 0 : getMerchandiseid().hashCode());
        return result;
    }
}