package com.shinowit.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class Memberinfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table memberinfo
     *
     * @mbggenerated Mon Jan 19 21:11:02 CST 2015
     */
    private static final long serialVersionUID = 1L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memberinfo.MemberID
     *
     * @mbggenerated Mon Jan 19 21:11:02 CST 2015
     */
    private String memberid;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memberinfo.MemberName
     *
     * @mbggenerated Mon Jan 19 21:11:02 CST 2015
     */
    private String membername;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memberinfo.Password
     *
     * @mbggenerated Mon Jan 19 21:11:02 CST 2015
     */
    private String password;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memberinfo.Email
     *
     * @mbggenerated Mon Jan 19 21:11:02 CST 2015
     */
    private String email;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memberinfo.Name
     *
     * @mbggenerated Mon Jan 19 21:11:02 CST 2015
     */
    private String name;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memberinfo.Balance
     *
     * @mbggenerated Mon Jan 19 21:11:02 CST 2015
     */
    private BigDecimal balance;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memberinfo.RegistDate
     *
     * @mbggenerated Mon Jan 19 21:11:02 CST 2015
     */
    private Date registdate;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memberinfo.Status
     *
     * @mbggenerated Mon Jan 19 21:11:02 CST 2015
     */
    private Boolean status;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memberinfo.Remark
     *
     * @mbggenerated Mon Jan 19 21:11:02 CST 2015
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memberinfo.MemberID
     *
     * @return the value of memberinfo.MemberID
     * @mbggenerated Mon Jan 19 21:11:02 CST 2015
     */
    public String getMemberid() {
        return memberid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memberinfo.MemberID
     *
     * @param memberid the value for memberinfo.MemberID
     * @mbggenerated Mon Jan 19 21:11:02 CST 2015
     */
    public void setMemberid(String memberid) {
        this.memberid = memberid == null ? null : memberid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memberinfo.MemberName
     *
     * @return the value of memberinfo.MemberName
     * @mbggenerated Mon Jan 19 21:11:02 CST 2015
     */
    public String getMembername() {
        return membername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memberinfo.MemberName
     *
     * @param membername the value for memberinfo.MemberName
     * @mbggenerated Mon Jan 19 21:11:02 CST 2015
     */
    public void setMembername(String membername) {
        this.membername = membername == null ? null : membername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memberinfo.Password
     *
     * @return the value of memberinfo.Password
     * @mbggenerated Mon Jan 19 21:11:02 CST 2015
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memberinfo.Password
     *
     * @param password the value for memberinfo.Password
     * @mbggenerated Mon Jan 19 21:11:02 CST 2015
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memberinfo.Email
     *
     * @return the value of memberinfo.Email
     * @mbggenerated Mon Jan 19 21:11:02 CST 2015
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memberinfo.Email
     *
     * @param email the value for memberinfo.Email
     * @mbggenerated Mon Jan 19 21:11:02 CST 2015
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memberinfo.Name
     *
     * @return the value of memberinfo.Name
     * @mbggenerated Mon Jan 19 21:11:02 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memberinfo.Name
     *
     * @param name the value for memberinfo.Name
     * @mbggenerated Mon Jan 19 21:11:02 CST 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memberinfo.Balance
     *
     * @return the value of memberinfo.Balance
     * @mbggenerated Mon Jan 19 21:11:02 CST 2015
     */
    public BigDecimal getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memberinfo.Balance
     *
     * @param balance the value for memberinfo.Balance
     * @mbggenerated Mon Jan 19 21:11:02 CST 2015
     */
    public void setBalance(BigDecimal balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memberinfo.RegistDate
     *
     * @return the value of memberinfo.RegistDate
     * @mbggenerated Mon Jan 19 21:11:02 CST 2015
     */
    public Date getRegistdate() {
        return registdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memberinfo.RegistDate
     *
     * @param registdate the value for memberinfo.RegistDate
     * @mbggenerated Mon Jan 19 21:11:02 CST 2015
     */
    public void setRegistdate(Date registdate) {
        this.registdate = registdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memberinfo.Status
     *
     * @return the value of memberinfo.Status
     * @mbggenerated Mon Jan 19 21:11:02 CST 2015
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memberinfo.Status
     *
     * @param status the value for memberinfo.Status
     * @mbggenerated Mon Jan 19 21:11:02 CST 2015
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memberinfo.Remark
     *
     * @return the value of memberinfo.Remark
     * @mbggenerated Mon Jan 19 21:11:02 CST 2015
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memberinfo.Remark
     *
     * @param remark the value for memberinfo.Remark
     * @mbggenerated Mon Jan 19 21:11:02 CST 2015
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memberinfo
     *
     * @mbggenerated Mon Jan 19 21:11:02 CST 2015
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Memberinfo other = (Memberinfo) that;
        return (this.getMemberid() == null ? other.getMemberid() == null : this.getMemberid().equals(other.getMemberid()))
                && (this.getMembername() == null ? other.getMembername() == null : this.getMembername().equals(other.getMembername()))
                && (this.getPassword() == null ? other.getPassword() == null : this.getPassword().equals(other.getPassword()))
                && (this.getEmail() == null ? other.getEmail() == null : this.getEmail().equals(other.getEmail()))
                && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
                && (this.getBalance() == null ? other.getBalance() == null : this.getBalance().equals(other.getBalance()))
                && (this.getRegistdate() == null ? other.getRegistdate() == null : this.getRegistdate().equals(other.getRegistdate()))
                && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
                && (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memberinfo
     *
     * @mbggenerated Mon Jan 19 21:11:02 CST 2015
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getMemberid() == null) ? 0 : getMemberid().hashCode());
        result = prime * result + ((getMembername() == null) ? 0 : getMembername().hashCode());
        result = prime * result + ((getPassword() == null) ? 0 : getPassword().hashCode());
        result = prime * result + ((getEmail() == null) ? 0 : getEmail().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getBalance() == null) ? 0 : getBalance().hashCode());
        result = prime * result + ((getRegistdate() == null) ? 0 : getRegistdate().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
        return result;
    }
}