package com.shinowit.entity;

import java.io.Serializable;

public class Memberaddress implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table memberaddress
     *
     * @mbggenerated Mon Jan 19 21:11:02 CST 2015
     */
    private static final long serialVersionUID = 1L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memberaddress.addressId
     *
     * @mbggenerated Mon Jan 19 21:11:02 CST 2015
     */
    private String addressid;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memberaddress.memberId
     *
     * @mbggenerated Mon Jan 19 21:11:02 CST 2015
     */
    private String memberid;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memberaddress.address
     *
     * @mbggenerated Mon Jan 19 21:11:02 CST 2015
     */
    private String address;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memberaddress.telephone
     *
     * @mbggenerated Mon Jan 19 21:11:02 CST 2015
     */
    private String telephone;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memberaddress.mobelphone
     *
     * @mbggenerated Mon Jan 19 21:11:02 CST 2015
     */
    private String mobelphone;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memberaddress.postalCode
     *
     * @mbggenerated Mon Jan 19 21:11:02 CST 2015
     */
    private String postalcode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memberaddress.addressId
     *
     * @return the value of memberaddress.addressId
     * @mbggenerated Mon Jan 19 21:11:02 CST 2015
     */
    public String getAddressid() {
        return addressid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memberaddress.addressId
     *
     * @param addressid the value for memberaddress.addressId
     * @mbggenerated Mon Jan 19 21:11:02 CST 2015
     */
    public void setAddressid(String addressid) {
        this.addressid = addressid == null ? null : addressid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memberaddress.memberId
     *
     * @return the value of memberaddress.memberId
     * @mbggenerated Mon Jan 19 21:11:02 CST 2015
     */
    public String getMemberid() {
        return memberid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memberaddress.memberId
     *
     * @param memberid the value for memberaddress.memberId
     * @mbggenerated Mon Jan 19 21:11:02 CST 2015
     */
    public void setMemberid(String memberid) {
        this.memberid = memberid == null ? null : memberid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memberaddress.address
     *
     * @return the value of memberaddress.address
     * @mbggenerated Mon Jan 19 21:11:02 CST 2015
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memberaddress.address
     *
     * @param address the value for memberaddress.address
     * @mbggenerated Mon Jan 19 21:11:02 CST 2015
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memberaddress.telephone
     *
     * @return the value of memberaddress.telephone
     * @mbggenerated Mon Jan 19 21:11:02 CST 2015
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memberaddress.telephone
     *
     * @param telephone the value for memberaddress.telephone
     * @mbggenerated Mon Jan 19 21:11:02 CST 2015
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memberaddress.mobelphone
     *
     * @return the value of memberaddress.mobelphone
     * @mbggenerated Mon Jan 19 21:11:02 CST 2015
     */
    public String getMobelphone() {
        return mobelphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memberaddress.mobelphone
     *
     * @param mobelphone the value for memberaddress.mobelphone
     * @mbggenerated Mon Jan 19 21:11:02 CST 2015
     */
    public void setMobelphone(String mobelphone) {
        this.mobelphone = mobelphone == null ? null : mobelphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memberaddress.postalCode
     *
     * @return the value of memberaddress.postalCode
     * @mbggenerated Mon Jan 19 21:11:02 CST 2015
     */
    public String getPostalcode() {
        return postalcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memberaddress.postalCode
     *
     * @param postalcode the value for memberaddress.postalCode
     * @mbggenerated Mon Jan 19 21:11:02 CST 2015
     */
    public void setPostalcode(String postalcode) {
        this.postalcode = postalcode == null ? null : postalcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memberaddress
     *
     * @mbggenerated Mon Jan 19 21:11:02 CST 2015
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Memberaddress other = (Memberaddress) that;
        return (this.getAddressid() == null ? other.getAddressid() == null : this.getAddressid().equals(other.getAddressid()))
                && (this.getMemberid() == null ? other.getMemberid() == null : this.getMemberid().equals(other.getMemberid()))
                && (this.getAddress() == null ? other.getAddress() == null : this.getAddress().equals(other.getAddress()))
                && (this.getTelephone() == null ? other.getTelephone() == null : this.getTelephone().equals(other.getTelephone()))
                && (this.getMobelphone() == null ? other.getMobelphone() == null : this.getMobelphone().equals(other.getMobelphone()))
                && (this.getPostalcode() == null ? other.getPostalcode() == null : this.getPostalcode().equals(other.getPostalcode()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memberaddress
     *
     * @mbggenerated Mon Jan 19 21:11:02 CST 2015
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getAddressid() == null) ? 0 : getAddressid().hashCode());
        result = prime * result + ((getMemberid() == null) ? 0 : getMemberid().hashCode());
        result = prime * result + ((getAddress() == null) ? 0 : getAddress().hashCode());
        result = prime * result + ((getTelephone() == null) ? 0 : getTelephone().hashCode());
        result = prime * result + ((getMobelphone() == null) ? 0 : getMobelphone().hashCode());
        result = prime * result + ((getPostalcode() == null) ? 0 : getPostalcode().hashCode());
        return result;
    }
}