package com.shinowit.entity;

import java.io.Serializable;

public class Merchandisecinfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table merchandisecinfo
     *
     * @mbggenerated Tue Dec 30 09:13:22 CST 2014
     */
    private static final long serialVersionUID = 1L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchandisecinfo.MerchandiseCID
     *
     * @mbggenerated Tue Dec 30 09:13:22 CST 2014
     */
    private String merchandisecid;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchandisecinfo.MerchandiseCName
     *
     * @mbggenerated Tue Dec 30 09:13:22 CST 2014
     */
    private String merchandisecname;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchandisecinfo.Status
     *
     * @mbggenerated Tue Dec 30 09:13:22 CST 2014
     */
    private Boolean status;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchandisecinfo.SortID
     *
     * @mbggenerated Tue Dec 30 09:13:22 CST 2014
     */
    private Integer sortid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchandisecinfo.MerchandiseCID
     *
     * @return the value of merchandisecinfo.MerchandiseCID
     * @mbggenerated Tue Dec 30 09:13:22 CST 2014
     */
    public String getMerchandisecid() {
        return merchandisecid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchandisecinfo.MerchandiseCID
     *
     * @param merchandisecid the value for merchandisecinfo.MerchandiseCID
     * @mbggenerated Tue Dec 30 09:13:22 CST 2014
     */
    public void setMerchandisecid(String merchandisecid) {
        this.merchandisecid = merchandisecid == null ? null : merchandisecid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchandisecinfo.MerchandiseCName
     *
     * @return the value of merchandisecinfo.MerchandiseCName
     * @mbggenerated Tue Dec 30 09:13:22 CST 2014
     */
    public String getMerchandisecname() {
        return merchandisecname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchandisecinfo.MerchandiseCName
     *
     * @param merchandisecname the value for merchandisecinfo.MerchandiseCName
     * @mbggenerated Tue Dec 30 09:13:22 CST 2014
     */
    public void setMerchandisecname(String merchandisecname) {
        this.merchandisecname = merchandisecname == null ? null : merchandisecname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchandisecinfo.Status
     *
     * @return the value of merchandisecinfo.Status
     * @mbggenerated Tue Dec 30 09:13:22 CST 2014
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchandisecinfo.Status
     *
     * @param status the value for merchandisecinfo.Status
     * @mbggenerated Tue Dec 30 09:13:22 CST 2014
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchandisecinfo.SortID
     *
     * @return the value of merchandisecinfo.SortID
     * @mbggenerated Tue Dec 30 09:13:22 CST 2014
     */
    public Integer getSortid() {
        return sortid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchandisecinfo.SortID
     *
     * @param sortid the value for merchandisecinfo.SortID
     * @mbggenerated Tue Dec 30 09:13:22 CST 2014
     */
    public void setSortid(Integer sortid) {
        this.sortid = sortid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchandisecinfo
     *
     * @mbggenerated Tue Dec 30 09:13:22 CST 2014
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Merchandisecinfo other = (Merchandisecinfo) that;
        return (this.getMerchandisecid() == null ? other.getMerchandisecid() == null : this.getMerchandisecid().equals(other.getMerchandisecid()))
                && (this.getMerchandisecname() == null ? other.getMerchandisecname() == null : this.getMerchandisecname().equals(other.getMerchandisecname()))
                && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
                && (this.getSortid() == null ? other.getSortid() == null : this.getSortid().equals(other.getSortid()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchandisecinfo
     *
     * @mbggenerated Tue Dec 30 09:13:22 CST 2014
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getMerchandisecid() == null) ? 0 : getMerchandisecid().hashCode());
        result = prime * result + ((getMerchandisecname() == null) ? 0 : getMerchandisecname().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getSortid() == null) ? 0 : getSortid().hashCode());
        return result;
    }
}