package com.shinowit.entity;

import java.io.Serializable;
import java.math.BigDecimal;

public class Merchandiseinfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table merchandiseinfo
     *
     * @mbggenerated Mon Jan 19 21:11:02 CST 2015
     */
    private static final long serialVersionUID = 1L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchandiseinfo.MerchandiseID
     *
     * @mbggenerated Mon Jan 19 21:11:02 CST 2015
     */
    private String merchandiseid;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchandiseinfo.MerchandiseCID
     *
     * @mbggenerated Mon Jan 19 21:11:02 CST 2015
     */
    private String merchandisecid;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchandiseinfo.UnitInfoID
     *
     * @mbggenerated Mon Jan 19 21:11:02 CST 2015
     */
    private Byte unitinfoid;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchandiseinfo.MerchandiseName
     *
     * @mbggenerated Mon Jan 19 21:11:02 CST 2015
     */
    private String merchandisename;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchandiseinfo.MerchandiseAB
     *
     * @mbggenerated Mon Jan 19 21:11:02 CST 2015
     */
    private String merchandiseab;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchandiseinfo.Price
     *
     * @mbggenerated Mon Jan 19 21:11:02 CST 2015
     */
    private BigDecimal price;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchandiseinfo.SaleStatus
     *
     * @mbggenerated Mon Jan 19 21:11:02 CST 2015
     */
    private Boolean salestatus;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchandiseinfo.Spec
     *
     * @mbggenerated Mon Jan 19 21:11:02 CST 2015
     */
    private String spec;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchandiseinfo.Descri
     *
     * @mbggenerated Mon Jan 19 21:11:02 CST 2015
     */
    private String descri;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchandiseinfo.PicPath
     *
     * @mbggenerated Mon Jan 19 21:11:02 CST 2015
     */
    private String picpath;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchandiseinfo.ClickCount
     *
     * @mbggenerated Mon Jan 19 21:11:02 CST 2015
     */
    private Integer clickcount;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchandiseinfo.Remark
     *
     * @mbggenerated Mon Jan 19 21:11:02 CST 2015
     */
    private String remark;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchandiseinfo.ProStatusID
     *
     * @mbggenerated Mon Jan 19 21:11:02 CST 2015
     */
    private String prostatusid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchandiseinfo.MerchandiseID
     *
     * @return the value of merchandiseinfo.MerchandiseID
     *
     * @mbggenerated Mon Jan 19 21:11:02 CST 2015
     */
    public String getMerchandiseid() {
        return merchandiseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchandiseinfo.MerchandiseID
     *
     * @param merchandiseid the value for merchandiseinfo.MerchandiseID
     *
     * @mbggenerated Mon Jan 19 21:11:02 CST 2015
     */
    public void setMerchandiseid(String merchandiseid) {
        this.merchandiseid = merchandiseid == null ? null : merchandiseid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchandiseinfo.MerchandiseCID
     *
     * @return the value of merchandiseinfo.MerchandiseCID
     *
     * @mbggenerated Mon Jan 19 21:11:02 CST 2015
     */
    public String getMerchandisecid() {
        return merchandisecid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchandiseinfo.MerchandiseCID
     *
     * @param merchandisecid the value for merchandiseinfo.MerchandiseCID
     *
     * @mbggenerated Mon Jan 19 21:11:02 CST 2015
     */
    public void setMerchandisecid(String merchandisecid) {
        this.merchandisecid = merchandisecid == null ? null : merchandisecid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchandiseinfo.UnitInfoID
     *
     * @return the value of merchandiseinfo.UnitInfoID
     *
     * @mbggenerated Mon Jan 19 21:11:02 CST 2015
     */
    public Byte getUnitinfoid() {
        return unitinfoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchandiseinfo.UnitInfoID
     *
     * @param unitinfoid the value for merchandiseinfo.UnitInfoID
     *
     * @mbggenerated Mon Jan 19 21:11:02 CST 2015
     */
    public void setUnitinfoid(Byte unitinfoid) {
        this.unitinfoid = unitinfoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchandiseinfo.MerchandiseName
     *
     * @return the value of merchandiseinfo.MerchandiseName
     *
     * @mbggenerated Mon Jan 19 21:11:02 CST 2015
     */
    public String getMerchandisename() {
        return merchandisename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchandiseinfo.MerchandiseName
     *
     * @param merchandisename the value for merchandiseinfo.MerchandiseName
     *
     * @mbggenerated Mon Jan 19 21:11:02 CST 2015
     */
    public void setMerchandisename(String merchandisename) {
        this.merchandisename = merchandisename == null ? null : merchandisename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchandiseinfo.MerchandiseAB
     *
     * @return the value of merchandiseinfo.MerchandiseAB
     *
     * @mbggenerated Mon Jan 19 21:11:02 CST 2015
     */
    public String getMerchandiseab() {
        return merchandiseab;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchandiseinfo.MerchandiseAB
     *
     * @param merchandiseab the value for merchandiseinfo.MerchandiseAB
     *
     * @mbggenerated Mon Jan 19 21:11:02 CST 2015
     */
    public void setMerchandiseab(String merchandiseab) {
        this.merchandiseab = merchandiseab == null ? null : merchandiseab.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchandiseinfo.Price
     *
     * @return the value of merchandiseinfo.Price
     *
     * @mbggenerated Mon Jan 19 21:11:02 CST 2015
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchandiseinfo.Price
     *
     * @param price the value for merchandiseinfo.Price
     *
     * @mbggenerated Mon Jan 19 21:11:02 CST 2015
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchandiseinfo.SaleStatus
     *
     * @return the value of merchandiseinfo.SaleStatus
     *
     * @mbggenerated Mon Jan 19 21:11:02 CST 2015
     */
    public Boolean getSalestatus() {
        return salestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchandiseinfo.SaleStatus
     *
     * @param salestatus the value for merchandiseinfo.SaleStatus
     *
     * @mbggenerated Mon Jan 19 21:11:02 CST 2015
     */
    public void setSalestatus(Boolean salestatus) {
        this.salestatus = salestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchandiseinfo.Spec
     *
     * @return the value of merchandiseinfo.Spec
     *
     * @mbggenerated Mon Jan 19 21:11:02 CST 2015
     */
    public String getSpec() {
        return spec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchandiseinfo.Spec
     *
     * @param spec the value for merchandiseinfo.Spec
     *
     * @mbggenerated Mon Jan 19 21:11:02 CST 2015
     */
    public void setSpec(String spec) {
        this.spec = spec == null ? null : spec.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchandiseinfo.Descri
     *
     * @return the value of merchandiseinfo.Descri
     *
     * @mbggenerated Mon Jan 19 21:11:02 CST 2015
     */
    public String getDescri() {
        return descri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchandiseinfo.Descri
     *
     * @param descri the value for merchandiseinfo.Descri
     *
     * @mbggenerated Mon Jan 19 21:11:02 CST 2015
     */
    public void setDescri(String descri) {
        this.descri = descri == null ? null : descri.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchandiseinfo.PicPath
     *
     * @return the value of merchandiseinfo.PicPath
     *
     * @mbggenerated Mon Jan 19 21:11:02 CST 2015
     */
    public String getPicpath() {
        return picpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchandiseinfo.PicPath
     *
     * @param picpath the value for merchandiseinfo.PicPath
     *
     * @mbggenerated Mon Jan 19 21:11:02 CST 2015
     */
    public void setPicpath(String picpath) {
        this.picpath = picpath == null ? null : picpath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchandiseinfo.ClickCount
     *
     * @return the value of merchandiseinfo.ClickCount
     *
     * @mbggenerated Mon Jan 19 21:11:02 CST 2015
     */
    public Integer getClickcount() {
        return clickcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchandiseinfo.ClickCount
     *
     * @param clickcount the value for merchandiseinfo.ClickCount
     *
     * @mbggenerated Mon Jan 19 21:11:02 CST 2015
     */
    public void setClickcount(Integer clickcount) {
        this.clickcount = clickcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchandiseinfo.Remark
     *
     * @return the value of merchandiseinfo.Remark
     *
     * @mbggenerated Mon Jan 19 21:11:02 CST 2015
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchandiseinfo.Remark
     *
     * @param remark the value for merchandiseinfo.Remark
     *
     * @mbggenerated Mon Jan 19 21:11:02 CST 2015
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchandiseinfo.ProStatusID
     *
     * @return the value of merchandiseinfo.ProStatusID
     *
     * @mbggenerated Mon Jan 19 21:11:02 CST 2015
     */
    public String getProstatusid() {
        return prostatusid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchandiseinfo.ProStatusID
     *
     * @param prostatusid the value for merchandiseinfo.ProStatusID
     *
     * @mbggenerated Mon Jan 19 21:11:02 CST 2015
     */
    public void setProstatusid(String prostatusid) {
        this.prostatusid = prostatusid == null ? null : prostatusid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchandiseinfo
     *
     * @mbggenerated Mon Jan 19 21:11:02 CST 2015
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Merchandiseinfo other = (Merchandiseinfo) that;
        return (this.getMerchandiseid() == null ? other.getMerchandiseid() == null : this.getMerchandiseid().equals(other.getMerchandiseid()))
                && (this.getMerchandisecid() == null ? other.getMerchandisecid() == null : this.getMerchandisecid().equals(other.getMerchandisecid()))
                && (this.getUnitinfoid() == null ? other.getUnitinfoid() == null : this.getUnitinfoid().equals(other.getUnitinfoid()))
                && (this.getMerchandisename() == null ? other.getMerchandisename() == null : this.getMerchandisename().equals(other.getMerchandisename()))
                && (this.getMerchandiseab() == null ? other.getMerchandiseab() == null : this.getMerchandiseab().equals(other.getMerchandiseab()))
                && (this.getPrice() == null ? other.getPrice() == null : this.getPrice().equals(other.getPrice()))
                && (this.getSalestatus() == null ? other.getSalestatus() == null : this.getSalestatus().equals(other.getSalestatus()))
                && (this.getSpec() == null ? other.getSpec() == null : this.getSpec().equals(other.getSpec()))
                && (this.getDescri() == null ? other.getDescri() == null : this.getDescri().equals(other.getDescri()))
                && (this.getPicpath() == null ? other.getPicpath() == null : this.getPicpath().equals(other.getPicpath()))
                && (this.getClickcount() == null ? other.getClickcount() == null : this.getClickcount().equals(other.getClickcount()))
                && (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()))
                && (this.getProstatusid() == null ? other.getProstatusid() == null : this.getProstatusid().equals(other.getProstatusid()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchandiseinfo
     *
     * @mbggenerated Mon Jan 19 21:11:02 CST 2015
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getMerchandiseid() == null) ? 0 : getMerchandiseid().hashCode());
        result = prime * result + ((getMerchandisecid() == null) ? 0 : getMerchandisecid().hashCode());
        result = prime * result + ((getUnitinfoid() == null) ? 0 : getUnitinfoid().hashCode());
        result = prime * result + ((getMerchandisename() == null) ? 0 : getMerchandisename().hashCode());
        result = prime * result + ((getMerchandiseab() == null) ? 0 : getMerchandiseab().hashCode());
        result = prime * result + ((getPrice() == null) ? 0 : getPrice().hashCode());
        result = prime * result + ((getSalestatus() == null) ? 0 : getSalestatus().hashCode());
        result = prime * result + ((getSpec() == null) ? 0 : getSpec().hashCode());
        result = prime * result + ((getDescri() == null) ? 0 : getDescri().hashCode());
        result = prime * result + ((getPicpath() == null) ? 0 : getPicpath().hashCode());
        result = prime * result + ((getClickcount() == null) ? 0 : getClickcount().hashCode());
        result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
        result = prime * result + ((getProstatusid() == null) ? 0 : getProstatusid().hashCode());
        return result;
    }
}